# Generated by Django 3.0.4 on 2020-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20200419_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
    ]
