# Generated by Django 3.0.4 on 2020-04-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200418_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
    ]
