# Generated by Django 3.0.4 on 2020-04-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200419_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='owner',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
