# Generated by Django 3.0.4 on 2020-04-20 06:24

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_auto_20200419_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=listing.models.get_upload_path),
        ),
    ]
