# Generated by Django 3.0.4 on 2020-04-20 06:25

from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20200420_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=listing.models.get_upload_path),
        ),
    ]
