# Generated by Django 3.0.4 on 2020-04-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20200420_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Order'),
        ),
    ]
